CREATE OR ALTER PROCEDURE removeItemfromCart(@pid VARCHAR(200))
AS 
BEGIN
	DELETE * FROM Cartbasket WHERE PID=@pid
END
EXEC removeItemfromCart '2329'

CREATE OR ALTER PROCEDURE clearCartItems(@cid VARCHAR(200))
AS
BEGIN
	UPDATE Cartbasket SET ISDELETED=0 WHERE CID = @cid
END