-- NOT NECESSARY
-- USE  ASSIGNMENT
-- go

  CREATE TABLE Products(
 PID VARCHAR(200) PRIMARY KEY,
 PNAME VARCHAR(155),
 PDESCRIPTION VARCHAR (155),
 PIMAGE VARCHAR(1000),
 PRICE INT,
 ISDELETED INT DEFAULT 0
 )