
#####
// registering a user
POST   http://localhost:8080/auth/sign-up
Content-Type: application/json

{

    "username":"bobo",
    "fullname":"Joyce Wambui ",
    "email":"bobo56@gmail.com",
    "phonenumber":"0729054323",
    "upassword":"Wamuyu@2023",
    "confirmpassword": "Wamuyu@2023"

}

# {
#     "username":"Njamba",
#     "fullname":"Sam k muchoki ",
#     "email":"skm55@gmail.com",
#     "phonenumber":"0788912323",
#     "upassword":"Wamuyu@2023",
#     "confirmpassword": "Wamuyu@2023"
# }


#####
// returns all users data
GET   http://localhost:8080/users


###
//getting user by email

GET http://localhost:8080/users/email/skm55@gmail.com



######
//get user by id
GET   http://localhost:8080/users/e7169ece-6b36-4bb8-b646-deb11b3d8841


#####
// update user dtails
PUT  http://localhost:8080/users/48408166-63ee-406c-9fd7-9270f5a56766
Content-Type: application/json

{
    
    "username":"bobo",
    "fullname":"Joyce Wambui ",
    "email":"bobo56@gmail.com",
    "phonenumber":"0729054323",
    "upassword":"Wamuyu@2023",
    "urole": "admin"
}


#####
// delete user details
DELETE http://localhost:8080/users/1



######
// login user
POST http://localhost:8080/auth/login/
Content-Type: application/json

{
    
    "email":"bobo56@gmail.com",
    "upassword":"Wamuyu@2023"

}




#####
/// products endpoints
POST http://localhost:8080/products
Content-Type: application/json
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVU0VSSUQiOiI0ODQwODE2Ni02M2VlLTQwNmMtOWZkNy05MjcwZjVhNTY3NjYiLCJVU0VSTkFNRSI6ImJvYm8iLCJGVUxMTkFNRSI6IkpveWNlIFdhbWJ1aSAiLCJFTUFJTCI6ImJvYm81NkBnbWFpbC5jb20iLCJQSE9ORU5VTUJFUiI6NzI5MDU0MzIzLCJVUk9MRSI6ImFkbWluIiwiSVNERUxFVEVEIjowLCJFTUFJTFNFTlQiOjAsImlhdCI6MTY4NTc4MTc1MywiZXhwIjoxNjg1OTA5NTUzfQ.GIdc2yLrCbVndxzEJ09Pr7xHR0SLTbFtVmSHUj6eknU 


{
    "pname":"Super Load Bread",
    "pdescription": "Never say bread, say superloaf",
    "pimage": "link",
    "price": 200,
    "pquantity": 2000,
    "pcategory": "snacks & eatables"
}

#####
/// get all products
GET http://localhost:8080/products


#####
/// get each product
GET http://localhost:8080/products/2327


#####
/// update product
PUT http://localhost:8080/products/2324
Content-Type:application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVU0VSSUQiOiI0ODQwODE2Ni02M2VlLTQwNmMtOWZkNy05MjcwZjVhNTY3NjYiLCJVU0VSTkFNRSI6ImJvYm8iLCJGVUxMTkFNRSI6IkpveWNlIFdhbWJ1aSAiLCJFTUFJTCI6ImJvYm81NkBnbWFpbC5jb20iLCJQSE9ORU5VTUJFUiI6NzI5MDU0MzIzLCJVUk9MRSI6ImFkbWluIiwiSVNERUxFVEVEIjowLCJFTUFJTFNFTlQiOjAsImlhdCI6MTY4NTk0Nzc5NSwiZXhwIjoxNjg2MDc1NTk1fQ.0V3yt1QYeYagSpaF40rpVxSxHKtmmoNNk2Ry1WGFW7Y

{
    
    "pname": "Keyboard",
    "pdescription": "Flexible Qwerty keyboard",
    "pimage": "https://www.google.com/imgres?imgurl=https%3A%2F%2Fwww.cnet.com%2Fa%2Fimg%2Fresize%2Fc2fb79b15d18f335e85fc4acd72910059cc9758b%2Fhub%2F2021%2F08%2F20%2F453e37bf-61cb-4e16-ad90-fd822bdc390a%2Fkeychron-k3-mechanical-keyboard.jpg%3Fauto%3Dwebp%26fit%3Dcrop%26height%3D900%26width%3D1200&tbnid=wkSaqhfXcyM9GM&vet=12ahUKEwisgYDIxKv_AhUXpycCHcBXDfsQMygLegUIARC4Ag..i&imgrefurl=https%3A%2F%2Fwww.cnet.com%2Ftech%2Fcomputing%2Fbest-keyboard%2F&docid=xTRdHjAsSuPj5M&w=1200&h=900&q=keyboard&ved=2ahUKEwisgYDIxKv_AhUXpycCHcBXDfsQMygLegUIARC4Ag",
    "pquantity": 700,
    "price": 100,
    "pcategory": "peripherals"
    
}


#####
/// delete product
DELETE http://localhost:8080/products/35820bc6-b405-4afe-9ea2-8b96f1c073e2
Content-Type:application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVU0VSSUQiOiI0ODQwODE2Ni02M2VlLTQwNmMtOWZkNy05MjcwZjVhNTY3NjYiLCJVU0VSTkFNRSI6ImJvYm8iLCJGVUxMTkFNRSI6IkpveWNlIFdhbWJ1aSAiLCJFTUFJTCI6ImJvYm81NkBnbWFpbC5jb20iLCJQSE9ORU5VTUJFUiI6NzI5MDU0MzIzLCJVUk9MRSI6ImFkbWluIiwiSVNERUxFVEVEIjowLCJFTUFJTFNFTlQiOjAsImlhdCI6MTY4NTc4MTc1MywiZXhwIjoxNjg1OTA5NTUzfQ.GIdc2yLrCbVndxzEJ09Pr7xHR0SLTbFtVmSHUj6eknU 




#####
// add to cart
POST http://localhost:8080/cart/2327
Content-Type: application/json


{  
    "email":"skm55@gmail.com"
}


#####
// view cart items
GET http://localhost:8080/cart


#####
// update cart
PUT http://localhost:8080/cart/7f2bdc5a-224e-4799-a288-1407d98d558a
Content-Type: application/json


{
    "pid": "2324",
    "pcount": 12
    
}


#####
// remove item from list
DELETE http://localhost:8080/cart/7fa7dcb1-f22f-4a0a-9db4-bb19e7b160d4

###
POST http://localhost:8080/orders
Content-Type: application/json


{
    "cid": "7fa7dcb1-f22f-4a0a-9db4-bb19e7b160d4"
}

####
// get all 
GET http://localhost:8080/orders


#####
// get orders by id
GET http://localhost:8080/orders/2f54b1e1-fb01-44e8-891e-2275d6de379a



#####
DELETE http://localhost:8080/orders/75456aab-443b-42b1-bd39-7b1832646627


######
PUT http://localhost:8080/orders/2f54b1e1-fb01-44e8-891e-2275d6de379a
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJVU0VSSUQiOiI0ODQwODE2Ni02M2VlLTQwNmMtOWZkNy05MjcwZjVhNTY3NjYiLCJVU0VSTkFNRSI6ImJvYm8iLCJGVUxMTkFNRSI6IkpveWNlIFdhbWJ1aSAiLCJFTUFJTCI6ImJvYm81NkBnbWFpbC5jb20iLCJQSE9ORU5VTUJFUiI6NzI5MDU0MzIzLCJVUk9MRSI6ImFkbWluIiwiSVNERUxFVEVEIjowLCJFTUFJTFNFTlQiOjAsImlhdCI6MTY4NTc4MTc1MywiZXhwIjoxNjg1OTA5NTUzfQ.GIdc2yLrCbVndxzEJ09Pr7xHR0SLTbFtVmSHUj6eknU 


{   
    "orderstatus":"Processing"
}







