
###
POST   http://localhost:4000/users
Content-Type: application/json


{
    "userName":"Wam",
    "fullName":"esther Wamuyu ",
    "email":"mucho.ijones@gmail.com",
    "phoneNumber":"078912323",
    "password":"Wamuyu@2023"
}


###
GET   http://localhost:4000/users


###
//getting user by email
GET http://localhost:4000/users/email/admin@example.com



###
GET   http://localhost:4000/users/8d34d657-111f-4126-b976-dcd355ef5413


###

PUT  http://localhost:4000/users/8d34d657-111f-4126-b976-dcd355ef5413
Content-Type: application/json

{
    "userName":"george Githaiga",
    "fullName":"George88 ",
    "email":"ggk8@gmail.com",
    "phoneNumber":"0712123556",
    "password":"452456789"
}

###
DELETE http://localhost:4000/users/67bd9253-8a1d-4ea0-83ef-446bbbe179d4


###
POST http://localhost:4000/users/login/
Content-Type:   application/json

{
    "password":"Admin@2023",
    "email": "admin2023@gmail.com"
      
}




#####
/// products endpoints
POST http://localhost:4000/products
Content-Type: application/json
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVkYjg3N2UyLTI2ODUtNGUxNy1hOGZhLTcwNzNkMjU1MGQ0MyIsInVzZXJOYW1lIjoiQURNSU4iLCJmdWxsTmFtZSI6IkVzdGhlciBNdWNob2tpICIsImVtYWlsIjoiYWRtaW4yMDIzQGdtYWlsLmNvbSIsInJvbGVzIjoiYWRtaW4iLCJlbWFpbFNlbnQiOjAsImlhdCI6MTY4NDE1NDM2MiwiZXhwIjoxNjg0MzI3MTYyfQ.r6n5TVf0nniaJgX7plnFDFSduhW51My_75jFyR-IfG4 


{
    "pname":"Grapeeees",
    "pdescription": "straight from the farm",
    "pimage": "link",
    "price": 230
}

#####
/// get all products
GET http://localhost:4000/products


#####
/// get each product
GET http://localhost:4000/products/cea2d354-59f3-4177-ae8e-674515c033c0


#####
/// update product
PUT http://localhost:4000/products/cea2d354-59f3-4177-ae8e-674515c033c0
Content-Type: application/json

{
    "pname": "Fish  & Omena",
    "pdescription": "straight from the fisher's hook",
    "pimage": "link",
    "price": 90
}


#####
/// delete product
DELETE http://localhost:4000/products/cea2d354-59f3-4177-ae8e-674515c033c0


#####
// add to cart
POST http://localhost:4000/cart/564
Content-Type: application/json


{
    "pname": "3 Idiots",
    "pdescription": "An Indian classic comedy",
    "price": 50
}


#####
// view cart items
GET http://localhost:4000/cart


#####
// update cart
PUT http://localhost:4000/cart/564
Content-Type: application/json


{
    "pname": "3 Idiots",
    "pdescription": "An Indian classic comedy",
    "price": 50
}
#####

// remove item from list
DELETE http://localhost:4000/cart/564

###
POST http://localhost:4000/orders
Content-Type: application/json

{   "pid":"253eb490-4687-47cb-98a8-fb3fbbf1032",
    "pname": "Grapeeees",
    "pdescription": "straight from the farm",
    "pimage": "link",
    "price": 90,
    "pcount":5
}

###

GET http://localhost:4000/orders/67277ed1-6829-470b-9ffc-46bd40b7da44

###
DELETE http://localhost:4000/orders/1422


####
// get all 
GET http://localhost:4000/orders

###
PUT http://localhost:4000/orders/67277ed1-6829-470b-9ffc-46bd40b7da44
Content-Type: application/json
token:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjVkYjg3N2UyLTI2ODUtNGUxNy1hOGZhLTcwNzNkMjU1MGQ0MyIsInVzZXJOYW1lIjoiQURNSU4iLCJmdWxsTmFtZSI6IkVzdGhlciBNdWNob2tpICIsImVtYWlsIjoiYWRtaW4yMDIzQGdtYWlsLmNvbSIsInJvbGVzIjoiYWRtaW4iLCJlbWFpbFNlbnQiOjAsImlhdCI6MTY4NDE1NDM2MiwiZXhwIjoxNjg0MzI3MTYyfQ.r6n5TVf0nniaJgX7plnFDFSduhW51My_75jFyR-IfG4 

{   
      "pid": "253eb490-4687-47cb-98a8-fb3fbbf1032",
    "pname": "Grapeeees",
    "price": 210,
    "pcount": 15
}