CREATE TABLE Orders(
ORDERID VARCHAR(200)PRIMARY KEY,
PID VARCHAR(200),
UID VARCHAR(200),
UEMAIL VARCHAR(150),
PNAME VARCHAR(155),
PRICE INT,
PCOUNT INT,
ORDERSTATUS VARCHAR(200),
ISDELETED INT DEFAULT 0,
)
