CREATE TABLE Users (
	USERID VARCHAR(200) PRIMARY KEY,
	USERNAME VARCHAR(100),
	FULLNAME VARCHAR(200),
	EMAIL VARCHAR(150) UNIQUE,
	PHONENUMBER INT,
	UPASSWORD VARCHAR(250),
	UROLE VARCHAR(150) DEFAULT 'user',
	ISDELETED INT DEFAULT 0,
	EMAILSENT INT DEFAULT 0
)