CREATE TABLE Cartbasket(
	CID VARCHAR(200) PRIMARY KEY,
	PID VARCHAR(200),
	UID VARCHAR(200),
	PNAME VARCHAR(155),
	PDESCRIPTION VARCHAR (155),
	PRICE INT,
	PCOUNT INT DEFAULT 1,
	FOREIGN KEY (PID) REFERENCES [dbo].[Products] (PID),
	FOREIGN KEY (UID) REFERENCES [dbo].[Users] (USERID)
)